# Generated by Django 5.2.7 on 2025-10-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_questions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
    ]
