# Generated by Django 5.2.7 on 2025-10-13 14:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_quizattempt_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='average_time_per_question',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='best_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='easy_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='easy_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='hard_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='hard_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='medium_attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='medium_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak'), ('accuracy', 'Accuracy'), ('practice', 'Practice'), ('mastery', 'Mastery'), ('consistency', 'Consistency')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.FloatField(default=0.0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('practice', 'Practice Session'), ('quiz', 'Quiz Session'), ('mock', 'Mock Test')], default='practice', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('all', 'All Levels'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='all', max_length=10)),
                ('subjects', models.ManyToManyField(related_name='practice_sessions', to='core.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('daily_goal_met', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PracticeSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='core.practicesession')),
                ('user_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.option')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
