# Generated by Django 5.2.7 on 2025-10-14 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprogress_average_time_per_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='core_catego_name_6ef604_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_at'], name='core_catego_created_873d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['user', 'date'], name='core_dailys_user_id_c2185b_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['date'], name='core_dailys_date_95991d_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question'], name='core_option_questio_0b36da_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['is_correct'], name='core_option_is_corr_47b7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'is_correct'], name='core_option_questio_630896_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'is_completed'], name='core_practi_user_id_faebc0_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'session_type'], name='core_practi_user_id_0132f2_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['is_completed', 'completed_at'], name='core_practi_is_comp_2f24f1_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['started_at'], name='core_practi_started_aeee6f_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['completed_at'], name='core_practi_complet_611401_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['score'], name='core_practi_score_7d3c45_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['session'], name='core_practi_session_cb85b3_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['question'], name='core_practi_questio_9dd800_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['user_answer'], name='core_practi_user_an_97252c_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['is_correct'], name='core_practi_is_corr_13ad61_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['session', 'is_correct'], name='core_practi_session_19b38f_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesessionquestion',
            index=models.Index(fields=['session', 'user_answer'], name='core_practi_session_8d7267_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'is_active'], name='core_questi_subject_be97df_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty', 'is_active'], name='core_questi_difficu_4f19fb_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'is_active'], name='core_questi_questio_c792ab_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='core_questi_is_acti_9c72ac_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='core_questi_created_700c69_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_published'], name='core_quiz_is_publ_a36af8_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_at'], name='core_quiz_created_e686bf_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'is_completed'], name='core_quizat_user_id_e9c829_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='core_quizat_user_id_122768_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['is_completed', 'completed_at'], name='core_quizat_is_comp_36bc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['started_at'], name='core_quizat_started_34852d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['completed_at'], name='core_quizat_complet_fb2ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category', 'is_active'], name='core_subjec_categor_262389_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='core_subjec_name_36111e_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['priority', 'is_active'], name='core_subjec_priorit_0007d1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='core_subjec_is_acti_80b240_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt'], name='core_useran_attempt_cc6ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question'], name='core_useran_questio_6dda38_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['is_correct'], name='core_useran_is_corr_6ba2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['answered_at'], name='core_useran_answere_3d70a6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user'], name='core_userpr_user_id_8db698_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['subject'], name='core_userpr_subject_9044e9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['accuracy'], name='core_userpr_accurac_7b6df6_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['last_attempt'], name='core_userpr_last_at_b58f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'subject'], name='core_userpr_user_id_a99ff2_idx'),
        ),
    ]
