# Generated by Django 5.2.7 on 2025-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cached_question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='cached_subject_count',
            field=models.IntegerField(default=0),
        ),
    ]
