# Generated by Django 5.2.7 on 2025-10-14 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_cached_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['question', 'is_active'], name='core_discus_questio_92c55b_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['user', 'created_at'], name='core_discus_user_id_f770ba_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['parent', 'is_active'], name='core_discus_parent__d820a3_idx'),
        ),
    ]
