# Generated by Django 5.2.7 on 2025-10-14 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_discussion_bookmarks_discussion_dislikes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discussion',
            name='core_discus_questio_92c55b_idx',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='question',
        ),
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='General Discussion', max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['is_active'], name='core_discus_is_acti_e3a131_idx'),
        ),
    ]
