# Generated by Django 5.2.7 on 2025-10-17 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_discussion_core_discus_questio_92c55b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('left', 'Left')], default='invited', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('time_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('duration', models.IntegerField(default=30)),
                ('max_participants', models.IntegerField(default=50)),
                ('session_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='core_discus_user_id_f770ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='core_discus_parent__d820a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='core_discus_is_acti_e3a131_idx',
        ),
        migrations.AddField(
            model_name='quizparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quiz_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='core.quiz'),
        ),
        migrations.AddField(
            model_name='quizparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.quizsession'),
        ),
        migrations.AddField(
            model_name='quizinvitation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.quizsession'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['session_code'], name='core_quizse_session_254ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['creator', 'status'], name='core_quizse_creator_840f08_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['scheduled_start', 'status'], name='core_quizse_schedul_9d24b4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizparticipant',
            index=models.Index(fields=['session', 'user'], name='core_quizpa_session_413bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizparticipant',
            index=models.Index(fields=['user', 'status'], name='core_quizpa_user_id_cac27d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.AddIndex(
            model_name='quizinvitation',
            index=models.Index(fields=['token'], name='core_quizin_token_a460b1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizinvitation',
            index=models.Index(fields=['email', 'accepted'], name='core_quizin_email_395a59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizinvitation',
            unique_together={('session', 'email')},
        ),
    ]
