# Generated by Django 5.2.7 on 2025-11-04 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adaptivequestion_advancedanalytics_challenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptivequestion',
            options={'ordering': ['-presented_at']},
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='actual_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='presented_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='was_answered_correctly',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adaptivequestion',
            name='response_time_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdaptiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(default=10)),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('ability_estimate', models.FloatField(default=0.5)),
                ('session_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='adaptivequestion',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.adaptivesession'),
        ),
    ]
