# Generated by Django 5.2.7 on 2025-11-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_adaptivequestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examsimulation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam_simulation', 'question')},
            },
        ),
        migrations.AddField(
            model_name='examsimulation',
            name='questions',
            field=models.ManyToManyField(blank=True, through='core.ExamQuestion', to='core.question'),
        ),
    ]
