# Generated by Django 5.2.7 on 2025-11-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_examquestion_examsimulation_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_type', models.CharField(choices=[('quick', 'Quick Match'), ('ranked', 'Ranked Battle'), ('friendly', 'Friendly Battle')], default='quick', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Opponent'), ('active', 'Battle Active'), ('completed', 'Battle Completed'), ('cancelled', 'Battle Cancelled')], default='waiting', max_length=20)),
                ('battle_code', models.CharField(max_length=8, unique=True)),
                ('question_count', models.IntegerField(default=10)),
                ('time_per_question', models.IntegerField(default=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_battles', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_time', models.FloatField(default=0.0)),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('battle', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BattleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('battle', 'question')},
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='questions',
            field=models.ManyToManyField(through='core.BattleQuestion', to='core.question'),
        ),
        migrations.CreateModel(
            name='BattleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.FloatField(default=0.0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('selected_options', models.ManyToManyField(to='core.option')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battleparticipant')),
            ],
            options={
                'indexes': [models.Index(fields=['battle', 'participant'], name='core_battle_battle__fecc44_idx'), models.Index(fields=['is_correct'], name='core_battle_is_corr_2e2bea_idx')],
                'unique_together': {('battle', 'participant', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['battle_code'], name='core_battle_battle__731da3_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', 'battle_type'], name='core_battle_status_926deb_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['creator', 'status'], name='core_battle_creator_cb1641_idx'),
        ),
    ]
